export const FETCH_SEARCHED_JOKES = 'FETCH_SEARCHED_JOKES';
export const FETCH_SEARCHED_JOKES_SUCCESS = 'FETCH_SEARCHED_JOKES_SUCCESS';
export const FETCH_SEARCHED_JOKES_FAILURE = 'FETCH_SEARCHED_JOKES_FAILURE';
